package oal.oracle.apps.fnd.qrtz.model.vo;

import oal.oracle.apps.fnd.qrtz.model.eo.OalqrtzJobRequestsEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 25 09:39:32 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OalqrtzJobRequestsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RequestId {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getRequestId();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setRequestId((Number)value);
            }
        }
        ,
        JobId {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getJobId();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        Description {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        ScheduledFireTime {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getScheduledFireTime();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setScheduledFireTime((Date)value);
            }
        }
        ,
        ActualFireTime {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getActualFireTime();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setActualFireTime((Date)value);
            }
        }
        ,
        CompletionTime {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getCompletionTime();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setCompletionTime((Date)value);
            }
        }
        ,
        StatusCode {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getStatusCode();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setStatusCode((String)value);
            }
        }
        ,
        ResultCode {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getResultCode();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setResultCode((String)value);
            }
        }
        ,
        ArgumentText {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getArgumentText();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setArgumentText((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CreatedBy {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        ScheduleNumber {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getScheduleNumber();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setScheduleNumber((String)value);
            }
        }
        ,
        JobName {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getJobName();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setJobName((String)value);
            }
        }
        ,
        JobType {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getJobType();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setJobType((String)value);
            }
        }
        ,
        LookupValuesForStatus {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getLookupValuesForStatus();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LookupValuesForResult {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getLookupValuesForResult();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LookupValuesForJobType {
            public Object get(OalqrtzJobRequestsVORowImpl obj) {
                return obj.getLookupValuesForJobType();
            }

            public void put(OalqrtzJobRequestsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OalqrtzJobRequestsVORowImpl object);

        public abstract void put(OalqrtzJobRequestsVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SCHEDULEDFIRETIME = AttributesEnum.ScheduledFireTime.index();
    public static final int ACTUALFIRETIME = AttributesEnum.ActualFireTime.index();
    public static final int COMPLETIONTIME = AttributesEnum.CompletionTime.index();
    public static final int STATUSCODE = AttributesEnum.StatusCode.index();
    public static final int RESULTCODE = AttributesEnum.ResultCode.index();
    public static final int ARGUMENTTEXT = AttributesEnum.ArgumentText.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int SCHEDULENUMBER = AttributesEnum.ScheduleNumber.index();
    public static final int JOBNAME = AttributesEnum.JobName.index();
    public static final int JOBTYPE = AttributesEnum.JobType.index();
    public static final int LOOKUPVALUESFORSTATUS = AttributesEnum.LookupValuesForStatus.index();
    public static final int LOOKUPVALUESFORRESULT = AttributesEnum.LookupValuesForResult.index();
    public static final int LOOKUPVALUESFORJOBTYPE = AttributesEnum.LookupValuesForJobType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OalqrtzJobRequestsVORowImpl() {
    }

    /**
     * Gets OalqrtzJobRequestsEO entity object.
     * @return the OalqrtzJobRequestsEO
     */
    public OalqrtzJobRequestsEOImpl getOalqrtzJobRequestsEO() {
        return (OalqrtzJobRequestsEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public Number getJobId() {
        return (Number) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for SCHEDULED_FIRE_TIME using the alias name ScheduledFireTime.
     * @return the SCHEDULED_FIRE_TIME
     */
    public Date getScheduledFireTime() {
        return (Date) getAttributeInternal(SCHEDULEDFIRETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEDULED_FIRE_TIME using the alias name ScheduledFireTime.
     * @param value value to set the SCHEDULED_FIRE_TIME
     */
    public void setScheduledFireTime(Date value) {
        setAttributeInternal(SCHEDULEDFIRETIME, value);
    }

    /**
     * Gets the attribute value for ACTUAL_FIRE_TIME using the alias name ActualFireTime.
     * @return the ACTUAL_FIRE_TIME
     */
    public Date getActualFireTime() {
        return (Date) getAttributeInternal(ACTUALFIRETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_FIRE_TIME using the alias name ActualFireTime.
     * @param value value to set the ACTUAL_FIRE_TIME
     */
    public void setActualFireTime(Date value) {
        setAttributeInternal(ACTUALFIRETIME, value);
    }

    /**
     * Gets the attribute value for COMPLETION_TIME using the alias name CompletionTime.
     * @return the COMPLETION_TIME
     */
    public Date getCompletionTime() {
        return (Date) getAttributeInternal(COMPLETIONTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPLETION_TIME using the alias name CompletionTime.
     * @param value value to set the COMPLETION_TIME
     */
    public void setCompletionTime(Date value) {
        setAttributeInternal(COMPLETIONTIME, value);
    }

    /**
     * Gets the attribute value for STATUS_CODE using the alias name StatusCode.
     * @return the STATUS_CODE
     */
    public String getStatusCode() {
        return (String) getAttributeInternal(STATUSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_CODE using the alias name StatusCode.
     * @param value value to set the STATUS_CODE
     */
    public void setStatusCode(String value) {
        setAttributeInternal(STATUSCODE, value);
    }

    /**
     * Gets the attribute value for RESULT_CODE using the alias name ResultCode.
     * @return the RESULT_CODE
     */
    public String getResultCode() {
        return (String) getAttributeInternal(RESULTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESULT_CODE using the alias name ResultCode.
     * @param value value to set the RESULT_CODE
     */
    public void setResultCode(String value) {
        setAttributeInternal(RESULTCODE, value);
    }

    /**
     * Gets the attribute value for ARGUMENT_TEXT using the alias name ArgumentText.
     * @return the ARGUMENT_TEXT
     */
    public String getArgumentText() {
        return (String) getAttributeInternal(ARGUMENTTEXT);
    }

    /**
     * Sets <code>value</code> as attribute value for ARGUMENT_TEXT using the alias name ArgumentText.
     * @param value value to set the ARGUMENT_TEXT
     */
    public void setArgumentText(String value) {
        setAttributeInternal(ARGUMENTTEXT, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobName.
     * @return the JobName
     */
    public String getJobName() {
        return (String) getAttributeInternal(JOBNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobName.
     * @param value value to set the  JobName
     */
    public void setJobName(String value) {
        setAttributeInternal(JOBNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobType.
     * @return the JobType
     */
    public String getJobType() {
        return (String) getAttributeInternal(JOBTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobType.
     * @param value value to set the  JobType
     */
    public void setJobType(String value) {
        setAttributeInternal(JOBTYPE, value);
    }

    /**
     * Gets the attribute value for SCHEDULE_NUMBER using the alias name ScheduleNumber.
     * @return the SCHEDULE_NUMBER
     */
    public String getScheduleNumber() {
        return (String) getAttributeInternal(SCHEDULENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEDULE_NUMBER using the alias name ScheduleNumber.
     * @param value value to set the SCHEDULE_NUMBER
     */
    public void setScheduleNumber(String value) {
        setAttributeInternal(SCHEDULENUMBER, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupValuesForStatus.
     */
    public RowSet getLookupValuesForStatus() {
        return (RowSet)getAttributeInternal(LOOKUPVALUESFORSTATUS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupValuesForResult.
     */
    public RowSet getLookupValuesForResult() {
        return (RowSet)getAttributeInternal(LOOKUPVALUESFORRESULT);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupValuesForJobType.
     */
    public RowSet getLookupValuesForJobType() {
        return (RowSet)getAttributeInternal(LOOKUPVALUESFORJOBTYPE);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
