package oal.oracle.apps.fnd.qrtz.model.vo;

import oal.oracle.apps.fnd.qrtz.model.service.QuartzAMImpl;
import oal.oracle.apps.fnd.qrtz.model.vo.common.OalqrtzJobsReadOnlyVO;

import oracle.adf.share.ADFContext;

import oracle.adf.share.security.SecurityContext;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 19 02:20:42 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OalqrtzJobsReadOnlyVOImpl extends ViewObjectImpl implements OalqrtzJobsReadOnlyVO {
    /**
     * This is the default constructor (do not remove).
     */
    public OalqrtzJobsReadOnlyVOImpl() {
    }

    public void executeWithJobId(int jobId) {
        setWhereClause("JOB_ID = "+jobId);
        executeQuery();
    }
}
