package oal.oracle.apps.fnd.qrtz.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 19 02:41:23 PST 2016
// ---------------------------------------------------------------------
public interface OalqrtzJobsReadOnlyVO extends ViewObject {
    void executeWithJobId(int jobId);
}
