package OAL.Oracle.apps.fnd.qrtz.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 08 06:09:08 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OalqrtzJobAccessGrantsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
public static final int Final=10;
int Last;

    public enum AttributesEnum {

        GrantId {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getGrantId();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setGrantId((Number)value);
            }
        }
        ,
        JobId {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getJobId();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        Role {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getRole();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setRole((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OalqrtzJobsEO {
            public Object get(OalqrtzJobAccessGrantsEOImpl obj) {
                return obj.getOalqrtzJobsEO();
            }

            public void put(OalqrtzJobAccessGrantsEOImpl obj, Object value) {
                obj.setOalqrtzJobsEO((OalqrtzJobsEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OalqrtzJobAccessGrantsEOImpl object);

        public abstract void put(OalqrtzJobAccessGrantsEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GRANTID = AttributesEnum.GrantId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int ROLE = AttributesEnum.Role.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int OALQRTZJOBSEO = AttributesEnum.OalqrtzJobsEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OalqrtzJobAccessGrantsEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oal.oracle.apps.fnd.qrtz.model.eo.OalqrtzJobAccessGrantsEO");
    }

    /**
     * Gets the attribute value for GrantId, using the alias name GrantId.
     * @return the GrantId
     */
    public Number getGrantId() {
        return (Number)getAttributeInternal(GRANTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantId.
     * @param value value to set the GrantId
     */
    public void setGrantId(Number value) {
        setAttributeInternal(GRANTID, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public Number getJobId() {
        return (Number)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for Role, using the alias name Role.
     * @return the Role
     */
    public String getRole() {
        return (String)getAttributeInternal(ROLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Role.
     * @param value value to set the Role
     */
    public void setRole(String value) {
        setAttributeInternal(ROLE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity OalqrtzJobsEOImpl.
     */
    public OalqrtzJobsEOImpl getOalqrtzJobsEO() {
        return (OalqrtzJobsEOImpl)getAttributeInternal(OALQRTZJOBSEO);
    }

    /**
     * Sets <code>value</code> as the associated entity OalqrtzJobsEOImpl.
     */
    public void setOalqrtzJobsEO(OalqrtzJobsEOImpl value) {
        setAttributeInternal(OALQRTZJOBSEO, value);
    }


    /**
     * @param grantId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number grantId) {
        return new Key(new Object[]{grantId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl sequence = new SequenceImpl("OALQRTZ_JOB_ACCESS_GRANTS_S",getDBTransaction());
        setGrantId(sequence.getSequenceNumber());
        setNewRowState(STATUS_INITIALIZED);
    }
}
