package oal.oracle.apps.fnd.qrtz.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 08 05:52:56 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OalqrtzJobsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ApplicationId {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getApplicationId();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setApplicationId((Number)value);
            }
        }
        ,
        JobId {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getJobId();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        JobName {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getJobName();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setJobName((String)value);
            }
        }
        ,
        Description {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getDescription();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Enabled {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getEnabled();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setEnabled((String)value);
            }
        }
        ,
        JobType {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getJobType();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setJobType((String)value);
            }
        }
        ,
        JobExecutable {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getJobExecutable();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setJobExecutable((String)value);
            }
        }
        ,
        JobExeOptions {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getJobExeOptions();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setJobExeOptions((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OalqrtzJobParamsEO {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getOalqrtzJobParamsEO();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OalqrtzJobAccessGrantsEO {
            public Object get(OalqrtzJobsEOImpl obj) {
                return obj.getOalqrtzJobAccessGrantsEO();
            }

            public void put(OalqrtzJobsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OalqrtzJobsEOImpl object);

        public abstract void put(OalqrtzJobsEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPLICATIONID = AttributesEnum.ApplicationId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int JOBNAME = AttributesEnum.JobName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ENABLED = AttributesEnum.Enabled.index();
    public static final int JOBTYPE = AttributesEnum.JobType.index();
    public static final int JOBEXECUTABLE = AttributesEnum.JobExecutable.index();
    public static final int JOBEXEOPTIONS = AttributesEnum.JobExeOptions.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int OALQRTZJOBPARAMSEO = AttributesEnum.OalqrtzJobParamsEO.index();
    public static final int OALQRTZJOBACCESSGRANTSEO = AttributesEnum.OalqrtzJobAccessGrantsEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OalqrtzJobsEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oal.oracle.apps.fnd.qrtz.model.eo.OalqrtzJobsEO");
    }

    /**
     * Gets the attribute value for ApplicationId, using the alias name ApplicationId.
     * @return the ApplicationId
     */
    public Number getApplicationId() {
        return (Number)getAttributeInternal(APPLICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApplicationId.
     * @param value value to set the ApplicationId
     */
    public void setApplicationId(Number value) {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public Number getJobId() {
        return (Number)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for JobName, using the alias name JobName.
     * @return the JobName
     */
    public String getJobName() {
        return (String)getAttributeInternal(JOBNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobName.
     * @param value value to set the JobName
     */
    public void setJobName(String value) {
        setAttributeInternal(JOBNAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Enabled, using the alias name Enabled.
     * @return the Enabled
     */
    public String getEnabled() {
        return (String)getAttributeInternal(ENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Enabled.
     * @param value value to set the Enabled
     */
    public void setEnabled(String value) {
        setAttributeInternal(ENABLED, value);
    }

    /**
     * Gets the attribute value for JobType, using the alias name JobType.
     * @return the JobType
     */
    public String getJobType() {
        return (String)getAttributeInternal(JOBTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobType.
     * @param value value to set the JobType
     */
    public void setJobType(String value) {
        setAttributeInternal(JOBTYPE, value);
    }

    /**
     * Gets the attribute value for JobExecutable, using the alias name JobExecutable.
     * @return the JobExecutable
     */
    public String getJobExecutable() {
        return (String)getAttributeInternal(JOBEXECUTABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobExecutable.
     * @param value value to set the JobExecutable
     */
    public void setJobExecutable(String value) {
        setAttributeInternal(JOBEXECUTABLE, value);
    }

    /**
     * Gets the attribute value for JobExeOptions, using the alias name JobExeOptions.
     * @return the JobExeOptions
     */
    public String getJobExeOptions() {
        return (String)getAttributeInternal(JOBEXEOPTIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobExeOptions.
     * @param value value to set the JobExeOptions
     */
    public void setJobExeOptions(String value) {
        setAttributeInternal(JOBEXEOPTIONS, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOalqrtzJobParamsEO() {
        return (RowIterator)getAttributeInternal(OALQRTZJOBPARAMSEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOalqrtzJobAccessGrantsEO() {
        return (RowIterator)getAttributeInternal(OALQRTZJOBACCESSGRANTSEO);
    }


    /**
     * @param jobId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number jobId) {
        return new Key(new Object[]{jobId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl sequence = new SequenceImpl("OALQRTZ_JOBS_S",getDBTransaction());
        setJobId(sequence.getSequenceNumber());
        setNewRowState(STATUS_INITIALIZED);
    }
}
