package oal.oracle.apps.fnd.qrtz.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 25 08:21:14 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OalqrtzJobRequestsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RequestId {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getRequestId();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setRequestId((Number)value);
            }
        }
        ,
        JobId {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getJobId();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        Description {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getDescription();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        ScheduledFireTime {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getScheduledFireTime();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setScheduledFireTime((Date)value);
            }
        }
        ,
        ActualFireTime {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getActualFireTime();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setActualFireTime((Date)value);
            }
        }
        ,
        CompletionTime {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getCompletionTime();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setCompletionTime((Date)value);
            }
        }
        ,
        StatusCode {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getStatusCode();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setStatusCode((String)value);
            }
        }
        ,
        ResultCode {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getResultCode();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setResultCode((String)value);
            }
        }
        ,
        ArgumentText {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getArgumentText();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setArgumentText((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ScheduleNumber {
            public Object get(OalqrtzJobRequestsEOImpl obj) {
                return obj.getScheduleNumber();
            }

            public void put(OalqrtzJobRequestsEOImpl obj, Object value) {
                obj.setScheduleNumber((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OalqrtzJobRequestsEOImpl object);

        public abstract void put(OalqrtzJobRequestsEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SCHEDULEDFIRETIME = AttributesEnum.ScheduledFireTime.index();
    public static final int ACTUALFIRETIME = AttributesEnum.ActualFireTime.index();
    public static final int COMPLETIONTIME = AttributesEnum.CompletionTime.index();
    public static final int STATUSCODE = AttributesEnum.StatusCode.index();
    public static final int RESULTCODE = AttributesEnum.ResultCode.index();
    public static final int ARGUMENTTEXT = AttributesEnum.ArgumentText.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int SCHEDULENUMBER = AttributesEnum.ScheduleNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OalqrtzJobRequestsEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oal.oracle.apps.fnd.qrtz.model.eo.OalqrtzJobRequestsEO");
    }

    /**
     * Gets the attribute value for RequestId, using the alias name RequestId.
     * @return the RequestId
     */
    public Number getRequestId() {
        return (Number)getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestId.
     * @param value value to set the RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public Number getJobId() {
        return (Number)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ScheduledFireTime, using the alias name ScheduledFireTime.
     * @return the ScheduledFireTime
     */
    public Date getScheduledFireTime() {
        return (Date)getAttributeInternal(SCHEDULEDFIRETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScheduledFireTime.
     * @param value value to set the ScheduledFireTime
     */
    public void setScheduledFireTime(Date value) {
        setAttributeInternal(SCHEDULEDFIRETIME, value);
    }

    /**
     * Gets the attribute value for ActualFireTime, using the alias name ActualFireTime.
     * @return the ActualFireTime
     */
    public Date getActualFireTime() {
        return (Date)getAttributeInternal(ACTUALFIRETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualFireTime.
     * @param value value to set the ActualFireTime
     */
    public void setActualFireTime(Date value) {
        setAttributeInternal(ACTUALFIRETIME, value);
    }

    /**
     * Gets the attribute value for CompletionTime, using the alias name CompletionTime.
     * @return the CompletionTime
     */
    public Date getCompletionTime() {
        return (Date)getAttributeInternal(COMPLETIONTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompletionTime.
     * @param value value to set the CompletionTime
     */
    public void setCompletionTime(Date value) {
        setAttributeInternal(COMPLETIONTIME, value);
    }

    /**
     * Gets the attribute value for StatusCode, using the alias name StatusCode.
     * @return the StatusCode
     */
    public String getStatusCode() {
        return (String)getAttributeInternal(STATUSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StatusCode.
     * @param value value to set the StatusCode
     */
    public void setStatusCode(String value) {
        setAttributeInternal(STATUSCODE, value);
    }

    /**
     * Gets the attribute value for ResultCode, using the alias name ResultCode.
     * @return the ResultCode
     */
    public String getResultCode() {
        return (String)getAttributeInternal(RESULTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResultCode.
     * @param value value to set the ResultCode
     */
    public void setResultCode(String value) {
        setAttributeInternal(RESULTCODE, value);
    }

    /**
     * Gets the attribute value for ArgumentText, using the alias name ArgumentText.
     * @return the ArgumentText
     */
    public String getArgumentText() {
        return (String)getAttributeInternal(ARGUMENTTEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArgumentText.
     * @param value value to set the ArgumentText
     */
    public void setArgumentText(String value) {
        setAttributeInternal(ARGUMENTTEXT, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for ScheduleNumber, using the alias name ScheduleNumber.
     * @return the ScheduleNumber
     */
    public String getScheduleNumber() {
        return (String)getAttributeInternal(SCHEDULENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScheduleNumber.
     * @param value value to set the ScheduleNumber
     */
    public void setScheduleNumber(String value) {
        setAttributeInternal(SCHEDULENUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param requestId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number requestId) {
        return new Key(new Object[]{requestId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl sequence = new SequenceImpl("OALQRTZ_JOB_REQUESTS_S",getDBTransaction());
        setRequestId(sequence.getSequenceNumber());
        setNewRowState(STATUS_INITIALIZED);
    }
}
