package oal.oracle.apps.fnd.qrtz.model.service;

import oal.oracle.apps.fnd.qrtz.model.service.common.QuartzAM;
import oal.oracle.apps.fnd.qrtz.model.vo.OalqrtzJobRequestsVOImpl;
import oal.oracle.apps.fnd.qrtz.model.vo.OalqrtzJobsReadOnlyVOImpl;
import oal.oracle.apps.fnd.qrtz.model.vo.ScheduledJobsVOImpl;

import oracle.adf.share.ADFContext;
import oracle.adf.share.security.SecurityContext;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewLinkImpl;

import oracle.jbo.server.ViewObjectImpl;

import org.apache.log4j.Logger;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 22 04:59:05 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuartzAMImpl extends ApplicationModuleImpl implements QuartzAM {
    private static final Logger log = Logger.getLogger(QuartzAMImpl.class);
    private String rolesList = null;
    /**
     * This is the default constructor (do not remove).
     */
    public QuartzAMImpl() {
    }

    /**
     * Container's getter for ScheduledJobsVO1.
     * @return ScheduledJobsVO1
     */
    public ScheduledJobsVOImpl getScheduledJobsVO1() {
        return (ScheduledJobsVOImpl)findViewObject("ScheduledJobsVO1");
    }

    /**
     * Container's getter for OalfndApplicationsVO1.
     * @return OalfndApplicationsVO1
     */
    public ViewObjectImpl getOalfndApplicationsVO1() {
        return (ViewObjectImpl)findViewObject("OalfndApplicationsVO1");
    }

    /**
     * Container's getter for OalqrtzJobsVO1.
     * @return OalqrtzJobsVO1
     */
    public ViewObjectImpl getOalqrtzJobsVO1() {
        return (ViewObjectImpl)findViewObject("OalqrtzJobsVO1");
    }

    /**
     * Container's getter for OalqrtzJobAccessGrantsVO1.
     * @return OalqrtzJobAccessGrantsVO1
     */
    public ViewObjectImpl getOalqrtzJobAccessGrantsVO1() {
        return (ViewObjectImpl)findViewObject("OalqrtzJobAccessGrantsVO1");
    }

    /**
     * Container's getter for OalqrtzJobParamsVO1.
     * @return OalqrtzJobParamsVO1
     */
    public ViewObjectImpl getOalqrtzJobParamsVO1() {
        return (ViewObjectImpl)findViewObject("OalqrtzJobParamsVO1");
    }

    /**
     * Container's getter for OalfndLookupValuesVO1.
     * @return OalfndLookupValuesVO1
     */
    public ViewObjectImpl getOalfndLookupValuesVO1() {
        return (ViewObjectImpl)findViewObject("OalfndLookupValuesVO1");
    }

    /**
     * Container's getter for OalqrtzJobsReadOnlyVO1.
     * @return OalqrtzJobsReadOnlyVO1
     */
    public OalqrtzJobsReadOnlyVOImpl getOalqrtzJobsReadOnlyVO1() {
        return (OalqrtzJobsReadOnlyVOImpl)findViewObject("OalqrtzJobsReadOnlyVO1");
    }

    /**
     * Container's getter for OalqrtzJobParamsReadOnlyVO1.
     * @return OalqrtzJobParamsReadOnlyVO1
     */
    public ViewObjectImpl getOalqrtzJobParamsReadOnlyVO1() {
        return (ViewObjectImpl)findViewObject("OalqrtzJobParamsReadOnlyVO1");
    }

    /**
     * Container's getter for OalqrtzJobToJobAccessVL1.
     * @return OalqrtzJobToJobAccessVL1
     */
    public ViewLinkImpl getOalqrtzJobToJobAccessVL1() {
        return (ViewLinkImpl)findViewLink("OalqrtzJobToJobAccessVL1");
    }

    /**
     * Container's getter for OalqrtzJobToJobParamsVL1.
     * @return OalqrtzJobToJobParamsVL1
     */
    public ViewLinkImpl getOalqrtzJobToJobParamsVL1() {
        return (ViewLinkImpl)findViewLink("OalqrtzJobToJobParamsVL1");
    }

    /**
     * Container's getter for OalqrtzJobToJobParamsReadOnlyVL1.
     * @return OalqrtzJobToJobParamsReadOnlyVL1
     */
    public ViewLinkImpl getOalqrtzJobToJobParamsReadOnlyVL1() {
        return (ViewLinkImpl)findViewLink("OalqrtzJobToJobParamsReadOnlyVL1");
    }
    
    public Number getScheduleNumber()
    {
        SequenceImpl sequence = new SequenceImpl("OALQRTZ_SCHEDULES_S",getDBTransaction());
        Number scheduleNum = sequence.getSequenceNumber();
        return scheduleNum;
        }

    /**
     * Container's getter for OalqrtzJobsReadOnlyVO2.
     * @return OalqrtzJobsReadOnlyVO2
     */
    public OalqrtzJobsReadOnlyVOImpl getJobsReadOnlyVOForJobName() {
        return (OalqrtzJobsReadOnlyVOImpl)findViewObject("JobsReadOnlyVOForJobName");
    }
    
    public String getJobName(int jobId)
    {
        log.debug("starting of getJobName jobId : "+jobId);
        String jobName = null;
        OalqrtzJobsReadOnlyVOImpl jobsVO = getJobsReadOnlyVOForJobName();
        jobsVO.executeWithJobId(jobId);
        Row jobRow = jobsVO.first();
        if(jobRow != null)
            jobName = (String) jobRow.getAttribute("JobName");
        log.debug("starting of getJobName jobId : "+jobId+" jobName : "+jobName);
        return jobName;
        }
    public boolean isAccessAllowed(String scheduleNumber)
    {
        log.debug("starting of isAccessAllowed scheduleNumber : "+scheduleNumber);
        boolean allowed = false;
        OalqrtzJobsReadOnlyVOImpl jobsVO = getJobsReadOnlyVOForJobName();
        jobsVO.executeWithJobId(Integer.parseInt(scheduleNumber.substring(0,scheduleNumber.indexOf("."))));
        Row jobRow = jobsVO.first();
        if(jobRow != null)
            allowed = true;
        log.debug("starting of isAccessAllowed allowed : "+allowed);
        return allowed;
        }


    /**
     * Container's getter for OalqrtzJobRequestsVO1.
     * @return OalqrtzJobRequestsVO1
     */
    public ViewObjectImpl getOalqrtzJobRequestsVO1() {
        return (ViewObjectImpl)findViewObject("OalqrtzJobRequestsVO1");
    }

    /**
     * Container's getter for OalfndLookupValuesVO3.
     * @return OalfndLookupValuesVO3
     */
    public ViewObjectImpl getOalfndLookupValuesForRoles() {
        return (ViewObjectImpl)findViewObject("OalfndLookupValuesForRoles");
    }
    public String getRolesList()
    {
        if(rolesList == null)
        {
        ViewObjectImpl rolesVO = getOalfndLookupValuesForRoles();
        rolesVO.executeQuery();
        SecurityContext sc = ADFContext.getCurrent().getSecurityContext();
        for ( Row row = rolesVO.first(); row != null; row = rolesVO.next() )  {
            String roleName = (String) row.getAttribute("LookupCode");
            if(sc.isUserInRole(roleName))
                if(rolesList != null)
                    rolesList = rolesList.concat(",'"+roleName+"'");
            else
                    rolesList = "'"+roleName+"'";
        }
//        rolesList = " in ("+rolesList+" ) ";
        }
        return rolesList;
    }

    /**
     * Container's getter for OalqrtzJobRequestsVO2.
     * @return OalqrtzJobRequestsVO2
     */
    public OalqrtzJobRequestsVOImpl getJobRequestsVOForGTrigger() {
        return (OalqrtzJobRequestsVOImpl)findViewObject("JobRequestsVOForGTrigger");
    }
}
