package oal.oracle.apps.fnd.qrtz.model.service.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 23 00:56:04 PST 2015
// ---------------------------------------------------------------------
public interface QuartzAM extends ApplicationModule {
    Number getScheduleNumber();
}
