package oal.oracle.apps.fnd.qrtz.model.vo.client;

import oal.oracle.apps.fnd.qrtz.model.vo.common.OalqrtzJobsReadOnlyVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 19 02:41:23 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OalqrtzJobsReadOnlyVOClient extends ViewUsageImpl implements OalqrtzJobsReadOnlyVO {
    /**
     * This is the default constructor (do not remove).
     */
    public OalqrtzJobsReadOnlyVOClient() {
    }

    public void executeWithJobId(int jobId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"executeWithJobId",new String [] {"int"},new Object[] {new Integer(jobId)});
        return;
    }
}
